[phases.setup]
nixPkgs = ["php", "composer", "mysql", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
